apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: $LETSENCRYPT_EMAIL
    server: $LETSENCRYPT_DIRECTORY
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
      - dns01:
          azureDNS:
            subscriptionID: $AZURE_SUBSCRIPTION_ID
            resourceGroupName: $RESOURCE_GROUP
            hostedZoneName: $DOMAIN
